TrainerNames:
	db "YOUNGSTER@"
	db "BUG CATCHER@"
	db "LASS@"
	db "SAILOR@"
	db "ADVENTURER@"
	db "ADVENTURER@"
	db "POKéMANIAC@"
	db "SUPER NERD@"
	db "HIKER@"
	db "BIKER@"
	db "BURGLAR@"
	db "ENGINEER@"
	db "JUGGLER@"
	db "FISHERMAN@"
	db "SWIMMER@"
	db "MYSTIC@"
	db "GAMBLER@"
	db "BEAUTY@"
	db "PSYCHIC@"
	db "TOUGH GUY@"
	db "JUGGLER@"
	db "EXPLORER@"
	db "BIRD KEEPER@"
	db "BLACKBELT@"
	db "RIVAL1@"
	db "PROF.OAK@"
	db "CHIEF@"
	db "SCIENTIST@"
	db "ATTICUS@"
	db "MYTH HUNTER@"
	db "EXPERT@"
	db "EXPERT@"
	db "BRUNO@"
	db "LARS@"
	db "TOBIAS@"
	db "TORI@"
	db "ERIKA@"
	db "HUGH@"
	db "ASTER@"
	db "SABRINA@"
	db "GENTLEMAN@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "LORELEI@"
	db "CHANNELER@"
	db "AGATHA@"
	db "LANCE@"
	db "LOGGER@"
	db "WYLDA@"
